[2023-06-01T21:10:13.040+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pj_br.DADOS_DEV.extract_data manual__2023-06-01T21:10:10.503424+00:00 [queued]>
[2023-06-01T21:10:13.056+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pj_br.DADOS_DEV.extract_data manual__2023-06-01T21:10:10.503424+00:00 [queued]>
[2023-06-01T21:10:13.056+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-01T21:10:13.056+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-01T21:10:13.056+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-01T21:10:13.076+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): DADOS_DEV.extract_data> on 2023-06-01 21:10:10.503424+00:00
[2023-06-01T21:10:13.083+0000] {standard_task_runner.py:55} INFO - Started process 7010 to run task
[2023-06-01T21:10:13.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pj_br', 'DADOS_DEV.extract_data', 'manual__2023-06-01T21:10:10.503424+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/pip_example.py', '--cfg-path', '/tmp/tmpfl0ucgkz']
[2023-06-01T21:10:13.091+0000] {standard_task_runner.py:83} INFO - Job 83: Subtask DADOS_DEV.extract_data
[2023-06-01T21:10:13.167+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_pj_br.DADOS_DEV.extract_data manual__2023-06-01T21:10:10.503424+00:00 [running]> on host e77927a9666c
[2023-06-01T21:10:13.289+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_pj_br
AIRFLOW_CTX_TASK_ID=DADOS_DEV.extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-01T21:10:10.503424+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-01T21:10:10.503424+00:00
[2023-06-01T21:10:13.290+0000] {logging_mixin.py:137} INFO - Reading file...
[2023-06-01T21:10:13.291+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pip_example.py", line 24, in extract
    print(kwargs['source'])
KeyError: 'source'
[2023-06-01T21:10:13.303+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_pj_br, task_id=DADOS_DEV.extract_data, execution_date=20230601T211010, start_date=20230601T211013, end_date=20230601T211013
[2023-06-01T21:10:13.326+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 83 for task DADOS_DEV.extract_data ('source'; 7010)
[2023-06-01T21:10:13.339+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-01T21:10:13.379+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
